### ISSUE TITLE
User Story :: Wall

### ISSUE THREAD

**Issue by Mernest** [varunsinghal/soen-341#105]
Initiator - parent or teacher

As a parent or teacher, I want to be able to post both images and comments on friend's wall, in order to share updates and news to them.

Story points: 15

Acceptance criteria
- Allow a user to view their own wall #106 
- Allow posting of text on the desired user's wall  (depending on whether friend or not) #107 
- Allow posting of images on the desired user's wall  (depending on whether friend or not) #108 
- Hide user's wall if another user is not a friend #109 
- Friends can like or dislike the post/images. #123

**Comment by varunsinghal** [comment]
All tasks have been closed.
