### ISSUE TITLE
User Story :: Messaging

### ISSUE THREAD

**Issue by kishortare** [varunsinghal/soen-341#2]
Messaging User Story

Initiator - Parent or Teacher

Goal - Private communication between the users of the system.

Portal allows parents and teachers to message and communicate with each other either by directly clicking on the message tab and typing the receiver id or via profile of the person. Any user can message any other user i.e. parent to parent, teacher to teacher, teacher to parent and vice-versa.

Priority - 

Story points - 

Acceptance criteria 

- A link should be visible on navigation bar to visit _messaging page_ #20 
- _Messaging page_ should display historical conversations #21 
- On click of any historical chat it should open the _conversation page_ between the users. #22 
- The _conversation page_ should display the other user and their chats. #23 
- The _conversation page_ should have a text box to enter the message. #24 
- The _conversation page_ to display the latest chat at the bottom most of the page. #26 
- A link to _compose new message_ should be visible on _messaging page_. #27 
- On  _compose page_, the user can type the username of the other user. The system should be able to hint the username as the user types in username in input box. #28 
- On  _compose page_, click of the hinted username, the input box should be filled by the clicked username. #29 
- On  _compose page_, a text box with message box should be visible. #30 
- On  _compose page_, "Send" button should be present below the message box. #31 
- On  _compose page_, the send button once clicked should send the message and other's user id to the back-end engine. #32 
- Back-end engine should make an entry in the database for the conversation. #33

**Comment by ofreish** [comment]
All the tasks are closed for the given user story. hence closing the issue.
