### ISSUE TITLE
HLR3 Parent Dashboard - Academic progress 

### ISSUE THREAD

**Issue by Mernest** [varunsinghal/soen-341#3]
Academic progress includes:
- Subject Name
- Subject Grade
- Class Average (could be added later)

Subject Name will allow the parent to see what course their children is currently taking. In order, to see their children's academic standing, the parent will also see the respective grade for each course. Finally, after implementing the above, another tab could be added that shows the class average for each course so the parents can know the strength and weaknesses of their child.

**Comment by varunsinghal** [comment]
Not required, hence closing the issue.
