### ISSUE TITLE
User Story :: Parent Dashboard -  Feed Story

### ISSUE THREAD

**Issue by Mernest** [varunsinghal/soen-341#4]
***Parent Dashboard User Story***

**Initiator** - Parent

**Goal** - Parent can see and comment on news feeds

As a Parent, i want to see posts by teachers about school events, social activities, etc. on my dashboard so that i can comment on the post.

**Priority** - 4

**Story Points** - 6

**Acceptance Criteria** 
- Parent is able to see posts by teachers. #34 
- Parent is able to see other teachers and parents comments on posts. #35 
- Parent is able to comment on all posts. #36

**Comment by admiralponce** [comment]
The front end will be compromised of a splash screen that includes a username login and password.
after logging in the webpage should know if the user is a teacher or a student.
Knowing who the user is, the front page should show for students their current courses and the feed and their grade. The teachers will get  to see all their students info, their feed stories and the course list.

**Comment by ofreish** [comment]
A bug has been opened as per the feedback against the feed story page of parent. #37

**Comment by ofreish** [comment]
Enhancement has been opened as per the feedback to allow parent to make a post on the feed story page.
