### ISSUE TITLE
HLR5 Teacher Dashboard - Current Courses

### ISSUE THREAD

**Issue by Mernest** [varunsinghal/soen-341#5]
All teacher feed story page will display the list of courses they are teaching. On click of individual courses will lead them to the respective course page.
On this course page, teacher can view the students enrolled in the class.
Also, it will be integrated with the messaging platform which will enable the teacher to connect with the parents of the student at individual level.

**Comment by varunsinghal** [comment]
Not required, hence closing the issue.
