### ISSUE TITLE
User Story :: Unit tests

### ISSUE THREAD

**Issue by ofreish** [varunsinghal/soen-341#65]
Add unit test case for service layer in Spring framework.
- [x] Controller layer #80 
- [x] Service layer #88 
- [x] Refactoring unit test cases to remove the fixture class. #219

**Comment by ofreish** [comment]
Total 38 unit test cases have been written, to test both controller and service layer.
![screenshot from 2018-10-29 14-57-11](https://user-images.githubusercontent.com/36609103/47673426-feb45100-db8a-11e8-9df6-5c371ef90266.png)

**Comment by varunsinghal** [comment]
Add unit test cases for group controller. And refactoring to remove the fixture class to be taken in sprint 6.

**Comment by varunsinghal** [comment]
![screenshot from 2018-11-14 06-52-51](https://user-images.githubusercontent.com/3696239/48481180-a2803c80-e7da-11e8-9e7e-ebe0689a5e43.png)
Total test cases : 59

**Comment by varunsinghal** [comment]
Refactoring to remove fixture class is done.
