### ISSUE TITLE
User Story :: Teacher Dashboard - Feed Story

### ISSUE THREAD

**Issue by Mernest** [varunsinghal/soen-341#7]
***Teacher Dashboard User Story***

**Initiator** - Teacher

**Goal** - Teacher can post news feeds

As a Teacher, i want to post about school events, social activities, etc. on my dashboard so that every user (Teacher or Parent) can see and comment on the post.

**Priority** - 4
**Story Points** - 8

**Acceptance Criteria** 
- Teacher is able to post something. #40 
- Teacher is able to see and comment on his post. #41 
- Teacher can see and comment on other's post. #42 
- Teacher can see comments added by other users on his post. #43

**Comment by varunsinghal** [comment]
An enhancement has been opened as per the feedback from the stakeholder. #38
